# Application related bindings
bind = $mainMod SHIFT, L, exec, hyprlock
bind = $mainMod, B, exec, $browser
bind = $mainMod, W, exec, waypaper --random
bind = $mainMod SHIFT, W, exec, waypaper
bind = $mainMod CTRL, W, exec, killall -SIGUSR1 waybar || waybar
bind = $mainMod, return, exec, $term 
bind = $mainMod, E, exec, $term yazi 
bind = $mainMod, SPACE, exec, pkill -x rofi || rofi -show drun -matching fuzzy
bind = $mainMod, V, exec, copyq toggle
