# Move focus
bind = $mainMod, L, movefocus, r
bind = $mainMod, H, movefocus, l
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

# Swap windows
bind = $mainMod CTRL, L, swapwindow, r
bind = $mainMod CTRL, H, swapwindow, l
bind = $mainMod CTRL, K, swapwindow, u
bind = $mainMod CTRL, J, swapwindow, d

# Close active window
bind = $mainMod, Q, killactive,

# Foggle fullscreen
bind = $mainMod, F, fullscreen, 0,

# Make window floating
bind = $mainMod SHIFT, F, togglefloating,


bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, U, togglesplit, # dwindle
