source = $HOME/.cache/wal/colors-hyprland.conf

source = conf/environment.conf

source = conf/autostart.conf

source = conf/monitor.conf

source = conf/input.conf

source = conf/keybindings.conf

source = conf/animations.conf

source = conf/windowrules.conf

source = conf/layerrules.conf

source = conf/general.conf

source = conf/decoration.conf

source = conf/layout.conf

source = conf/misc.conf
