env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

env = XCURSOR_THEME,Bibata-Modern-Classic
env = HYPRCURSOR_THEME,Bibata-Modern-Classic

env = GTK_THEME,Adwaita:dark
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt6ct
