# XDG env vars
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# Mouse cursor size
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# Mouse cursor theme
env = XCURSOR_THEME,Bibata-Modern-Classic
env = HYPRCURSOR_THEME,Bibata-Modern-Classic

# GTK theming
env = GTK_THEME,adw-gtk3-dark

# QT theming
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,hyprqt6engine
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
