general {
    gaps_in = 8
    gaps_out = 8

    border_size = 2

    col.active_border = $color1
    col.inactive_border = $background

    resize_on_border = false

    allow_tearing = false

    layout = dwindle
}
